export const FETCH_USER = 'FETCH_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
